# Generated by Django 5.2.1 on 2025-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
